-- AlterTable
ALTER TABLE "Asset" ALTER COLUMN "buyPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maintenancePrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "replacementPrice" SET DATA TYPE DOUBLE PRECISION;
